### ISSUE TITLE
update PT translations to be up-t-date with EN

### ISSUE THREAD

**Issue by thomasmodeneis** [AdoptOpenJDK/adoptopenjdk-getting-started-kit#21]

**Comment by allandequeiroz** [comment]
Just did.
https://github.com/AdoptOpenJDK/adoptopenjdk-getting-started-kit/pull/39

**Comment by allandequeiroz** [comment]
@neomatrix369 maybe we can get rid of this one.

**Comment by neomatrix369** [comment]
You can mention all the PRs in the comments here - closing now
