### ISSUE TITLE
sync pt with en

### ISSUE THREAD

**Issue by thomasmodeneis** [AdoptOpenJDK/adoptopenjdk-getting-started-kit#35]
tasks:

sync main files on root, few files have been removed and contributors is merged with contribute.
check for other things to sync like quickstart.md and delete un-used images.

add translated folder how-to-navigate
add translated folder docker-images

check all other folders for other tasks pending and create separated tickets from it

**Comment by thomasmodeneis** [comment]
refer to https://github.com/thomasmodeneis/adoptopenjdk-getting-started-kit/issues/1

**Comment by thomasmodeneis** [comment]
translate /intermediate-steps/change_the_randomjava_class.md

**Comment by thomasmodeneis** [comment]
same applies for how_to_use_jtreg_-_java_regression_test_harness.md

**Comment by allandequeiroz** [comment]
Just did it.
https://github.com/AdoptOpenJDK/adoptopenjdk-getting-started-kit/pull/39

**Comment by allandequeiroz** [comment]
@neomatrix369 maybe we can get rid of this one.

**Comment by neomatrix369** [comment]
You can mention all the PRs in the comments here - closing now
